# Generated by Django 2.1.1 on 2018-09-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('year', models.PositiveSmallIntegerField()),
                ('starts', models.DateField()),
                ('ends', models.DateField()),
                ('num_stages', models.PositiveSmallIntegerField(default=1)),
                ('link', models.URLField(blank=True)),
                ('teams_per_league', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('free_stages', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_budget', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team_roster_size', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_live', models.BooleanField(default=0)),
                ('is_locked', models.BooleanField(default=1)),
                ('is_classic', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'races',
            },
        ),
    ]
