# Generated by Django 2.1.1 on 2018-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0003_auto_20180930_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
