# Generated by Django 2.1.1 on 2018-10-01 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_auto_20180930_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bib', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('team', models.CharField(max_length=200)),
                ('dnf', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=200, null=True)),
                ('jersey_hunt', models.CharField(blank=True, max_length=200, null=True)),
                ('rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Rider')),
            ],
            options={
                'db_table': 'participations',
            },
        ),
    ]
