# Generated by Django 2.1.1 on 2018-10-01 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_participation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participation',
            old_name='rank',
            new_name='val',
        ),
    ]
