# Generated by Django 2.1.1 on 2018-12-29 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='slug',
        ),
    ]
