# Generated by Django 2.1.1 on 2018-12-29 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0009_remove_team_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('has_drafted', models.BooleanField(default=0)),
                ('is_private', models.BooleanField(default=0)),
                ('is_full', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
            ],
            options={
                'db_table': 'leagues',
            },
        ),
    ]
