# Generated by Django 2.1.1 on 2018-12-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='password',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='races.League'),
        ),
    ]
