# Generated by Django 2.1.1 on 2018-12-29 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0011_auto_20181229_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
    ]
