# Generated by Django 2.1.1 on 2018-12-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0012_auto_20181229_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='distance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='end_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='start_city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
