# Generated by Django 2.1.1 on 2018-12-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_auto_20181230_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_classic',
            field=models.BooleanField(default=0),
        ),
    ]
