# Generated by Django 2.1.1 on 2019-01-03 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0015_finalresult_jersey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_num', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('distance', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('stage_type', models.CharField(blank=True, max_length=200, null=True)),
                ('depart_city', models.CharField(blank=True, max_length=200, null=True)),
                ('depart_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('depart_long', models.CharField(blank=True, max_length=200, null=True)),
                ('arrive_city', models.CharField(blank=True, max_length=200, null=True)),
                ('arrive_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('arrive_long', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField()),
                ('is_doubled', models.BooleanField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='race',
        ),
        migrations.RemoveField(
            model_name='jersey',
            name='rider',
        ),
        migrations.DeleteModel(
            name='Jersey',
        ),
    ]
