# Generated by Django 2.1.1 on 2019-01-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0017_jersey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jersey',
            name='bib',
        ),
    ]
