# Generated by Django 2.1.1 on 2019-01-03 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0018_remove_jersey_bib'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
