# Generated by Django 2.1.1 on 2019-01-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0022_auto_20190104_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rider',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
