# Generated by Django 2.1.1 on 2019-01-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0025_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='riders',
            field=models.ManyToManyField(to='races.Rider'),
        ),
    ]
