# Generated by Django 2.1.1 on 2019-01-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0026_post_riders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
            ],
        ),
        migrations.RenameField(
            model_name='participation',
            old_name='team',
            new_name='squad',
        ),
        migrations.AddField(
            model_name='pick',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='races.Participation'),
        ),
        migrations.AddField(
            model_name='pick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='riders',
            field=models.ManyToManyField(through='races.Pick', to='races.Participation'),
        ),
    ]
