# Generated by Django 2.1.1 on 2019-01-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0027_auto_20190106_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='riders',
            field=models.ManyToManyField(through='races.Participation', to='races.Rider'),
        ),
    ]
