# Generated by Django 2.1.1 on 2019-01-06 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0028_race_riders'),
    ]

    operations = [
        migrations.CreateModel(
            name='RosterPick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Participation')),
            ],
        ),
        migrations.RemoveField(
            model_name='pick',
            name='race',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='pick',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='riders',
        ),
        migrations.DeleteModel(
            name='Pick',
        ),
        migrations.AddField(
            model_name='rosterpick',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Team'),
        ),
    ]
