# Generated by Django 2.1.1 on 2019-01-06 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0029_auto_20190106_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Participation')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picks', models.ManyToManyField(to='races.Pick')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='rosterpick',
            name='race',
        ),
        migrations.RemoveField(
            model_name='rosterpick',
            name='rider',
        ),
        migrations.RemoveField(
            model_name='rosterpick',
            name='team',
        ),
        migrations.DeleteModel(
            name='RosterPick',
        ),
    ]
