# Generated by Django 2.1.1 on 2019-01-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0030_auto_20190106_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='rider',
        ),
        migrations.AlterField(
            model_name='roster',
            name='picks',
            field=models.ManyToManyField(to='races.Participation'),
        ),
        migrations.DeleteModel(
            name='Pick',
        ),
    ]
