# Generated by Django 2.1.1 on 2019-01-06 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0031_auto_20190106_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='is_live',
            field=models.BooleanField(default=0, verbose_name='Live?'),
        ),
    ]
