# Generated by Django 2.1.1 on 2019-01-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0032_auto_20190106_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='is_classic',
            field=models.BooleanField(default=0, verbose_name='Classic?'),
        ),
        migrations.AlterField(
            model_name='race',
            name='is_locked',
            field=models.BooleanField(default=1, verbose_name='Locked?'),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('team', 'race')},
        ),
        migrations.AlterModelTable(
            name='roster',
            table='rosters',
        ),
    ]
