# Generated by Django 2.1.1 on 2019-01-06 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0033_auto_20190106_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='race',
            field=models.ForeignKey(limit_choices_to={'is_classic': True}, on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
    ]
