# Generated by Django 2.1.1 on 2019-01-20 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0036_siteoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteoptions',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
