# Generated by Django 2.1.1 on 2019-01-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0037_auto_20190120_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteoptions',
            old_name='key',
            new_name='opt_key',
        ),
        migrations.RenameField(
            model_name='siteoptions',
            old_name='value',
            new_name='opt_value',
        ),
    ]
