# Generated by Django 2.1.1 on 2019-01-20 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0038_auto_20190120_0156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteOptions',
            new_name='SiteOption',
        ),
    ]
