# Generated by Django 2.1.1 on 2019-01-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0039_auto_20190120_0202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
