# Generated by Django 2.1.1 on 2019-01-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0040_auto_20190122_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='picks',
            field=models.ManyToManyField(blank=True, null=True, to='races.Participation'),
        ),
    ]
