# Generated by Django 2.1.1 on 2019-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0043_auto_20190131_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='classics_points',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
