# Generated by Django 2.1.1 on 2019-02-01 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0044_participation_classics_points'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='finalresult',
            unique_together={('race', 'place')},
        ),
    ]
