# Generated by Django 2.1.1 on 2019-02-03 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0045_auto_20190201_0433'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='pts',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
